apt_packages:
  - ca-certificates
  - cowsay
  - curl
  - git
  - gnupg-agent
  - htop
  - jq
  - nodejs
  - software-properties-common
  - traceroute
  - tree
  - vim
  - whois
  - zsh
  - g++
  - gcc
  - libtool
  - make
  - python3
  - python3-pip
