---
- name: Ensure the system can use the HTTPS transport for APT
  stat: path=/usr/lib/apt/methods/https
  register: apt_https_transport

- name: Install HTTPS transport for APT
  apt: pkg=apt-transport-https state=present

- name: Enable all repositories in sources.list
  replace: dest=/etc/apt/sources.list regexp='^#\s?deb(.+)http://(.+)/ubuntu(.+)$' replace='deb\1http://\2/ubuntu\3' backup=yes

- name: Install APT Packages
  apt: pkg={{ apt_packages }} state=latest update_cache=yes

- name: Upgrade installed packages
  apt: upgrade=yes

- name: Setup Configuration Files
  file:
    dest: "{{ item.dest }}"
    force: yes
    state: link
    src: "{{ ansible_env.PWD }}/roles/ubuntu/files/{{ item.filename }}"
  with_items:
    - { filename: ansible.cfg, dest: ~/.ansible.cfg }

- name: Setup gitconfig
  template:
    dest: ~/.gitconfig
    src: ../template/gitconfig.j2
    force: no

- name: Update to latest PIP
  pip:
    name: pip
    state: latest

- name: Remove useless items
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "~/Templates"
    - "~/Public"
    - "~/examples.desktop"

- name: Ansible check if code dir exists.
  stat:
    path: /home/meck/code
  register: code

- name: Create Code dir (if not exists).
  file:
    path: /home/meck/code
    state: directory
  when: code.stat.exists == false

- include_tasks: docker.yml
- include_tasks: zsh.yml
- include_tasks: vscode.yml
